### ISSUE TITLE
Fix web page console error (non-blocking)

### ISSUE THREAD

**Issue by sahendrickson** [DaVinciSchools/leo#31]
Fix error with webpages that prints the following to the web console:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'icons')
    at infield.chunk.js:1:3282785
    at d (infield.chunk.js:1:3276602)
    at Generator.<anonymous> (infield.chunk.js:1:3277943)
    at Generator.next (infield.chunk.js:1:3276965)
    at r (3.chunk.js:1:17156)
    at u (3.chunk.js:1:17359)
    at 3.chunk.js:1:17418
    at new Promise (<anonymous>)
    at 3.chunk.js:1:17299
    at p (infield.chunk.js:1:3282585)

**Comment by yanCode** [comment]
reporting a bug like this, it's better to include some more details, like in which url it prints this error.

**Comment by sahendrickson** [comment]
@yanCode You're right. Sorry about that. I actually fixed this as a side effect of a different change I made. So, it's no longer relevant.
